### ISSUE TITLE
Could not install from ... as it does not contain a package.json file.

### ISSUE THREAD

**Issue by mateuszbem** [thisissoon/angular-scrollspy#15] opened 2018-12-12 12:55 UTC
Could not install from "@thisissoon\{angular-scrollspy,angular-inviewport}" as it does not contain a package.json file.

Is something wrong with repo?
Regards!!!

**Comment by jenniferkaplannyc** [comment] 2018-12-12 18:45
I successfully downloaded it yesterday by running the command `npm i @thisissoon/{angular-scrollspy,angular-inviewport} --save`. I am using NPM version `6.4.1`and Node version `10.13.0`.

**Comment by edoparearyee** [comment] 2018-12-16 18:48
@mateuszbem running `npm i @thisissoon/{angular-scrollspy,angular-inviewport}` appears to work for me. Closing as I am unable to reproduce this.

**Closed by edoparearyee** 2018-12-16 18:48 UTC

**Comment by neon98** [comment] 2019-02-11 09:25
same with me! It shows below error.

```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@thisissoon\{angular-scrollspy,angular-inviewport}" as it does not contain a package.json file.
```

**Comment by edoparearyee** [comment] 2019-02-18 12:54
@neon98 the command should be `npm i @thisissoon/{angular-scrollspy,angular-inviewport}` 

**Note** the forward slash `/` instead of a backslash
